### ISSUE TITLE
CreateThreadObject with callback

### ISSUE THREAD

**Issue by wisewebpt** [ChristianEhlscheid/vfp2c32#29]
Hi,

When calling CreateThreadObject using the callback, it always returns "Cannot find entry point GetIDispatch in the DLL".
Without the callback it works.

Also, when using CLSCTX_LOCAL_SERVER (0x04 I assume) context, it always errors with a localized message about class not being registered.

Furthermore, although the code continues to execute after calling the function, it still blocks the UI while running.
It's the first time using it, so unsure if doing something wrong.

Thanks.

**Comment by ChristianEhlscheid** [comment]
Hello,

I've fixed the "Cannot fid entry point GetIDispatch .." error.

The problem you have with CLSCTX_LOCAL_SERVER I cannot currently resolve without further info,
please check the following:
- is the object you're trying to instantiate createable with a call to CREATEOBJECT

The calls should be non blocking, this only works if the object doesn't call any UI code itself though.

**Comment by wisewebpt** [comment]
Hey,


So about the blocking issue, turns out it was because I was using local variables, with public variables everything works fine. Makes sense in hindsight!

I still get the GetIDispatch error though, I'm attaching the simplest example I could come up with, maybe I'm doing something wrong.

[Multithread Example.zip](https://github.com/ChristianEhlscheid/vfp2c32/files/12557135/Multithread.Example.zip)


Thanks!

**Comment by ChristianEhlscheid** [comment]
Hello,

thank you for the bug report, I've just updated the latest release with a functioning version.

**Comment by wisewebpt** [comment]
Confirmed, all working fine.

Thanks a lot!
